backend:
  name: git-gateway
  branch: main

media_folder: "blog/uploads"
public_folder: "/blog/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "thumbnail", widget: "image" }
